/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function WoodenTruss(props) {
  const { nodes, materials } = useGLTF('/models/WoodenTruss.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_1.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_2.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_3.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_4.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_5.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_6.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_7.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_8.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_9.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_10.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_11.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_12.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_13.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_14.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_15.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_16.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_17.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_18.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_19.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_20.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_21.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_22.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_23.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_24.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_25.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_26.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_27.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_28.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_29.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_30.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_31.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_32.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_33.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_34.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_35.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_36.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_37.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_38.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_39.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_40.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_41.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_42.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_43.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_44.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_45.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_46.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_47.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_48.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_49.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_50.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_51.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_52.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_53.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_54.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_55.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_56.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_57.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_58.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_59.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_60.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_61.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_62.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_63.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_64.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_65.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_66.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_67.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_68.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_69.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_70.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_71.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_72.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_73.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_74.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_75.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_76.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_77.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_78.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_79.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_80.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_81.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_82.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_83.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_84.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_85.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_86.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_87.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_88.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_89.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_90.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_91.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_92.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_93.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_94.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_95.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_96.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_97.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_98.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_99.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_100.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_101.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_102.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_103.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_104.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_105.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_106.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_107.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_108.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_109.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_110.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_111.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_112.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_113.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_114.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_115.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_116.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_117.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_118.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_119.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_120.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_121.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_122.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_123.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_124.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_125.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_126.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_127.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_128.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_129.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_130.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_131.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_132.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_133.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_134.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_135.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_136.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_137.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_138.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_139.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_140.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_141.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_142.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_143.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_144.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_145.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_146.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_147.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_148.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_149.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_150.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_151.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_152.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_153.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_154.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_155.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_156.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_157.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_158.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_159.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_160.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_161.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_162.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_163.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_164.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_165.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_166.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_167.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_168.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_169.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_170.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_171.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_172.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_173.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_174.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_175.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_176.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_177.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_178.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_179.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_180.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_181.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_182.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_183.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_184.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_185.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_186.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_187.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_188.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_189.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_190.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_191.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_192.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_193.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_194.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_195.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_196.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_197.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_198.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_199.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_200.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_201.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_202.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_203.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_204.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_205.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_206.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_207.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_208.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_209.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_210.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_211.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_212.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_213.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_214.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_215.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_216.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_217.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_218.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_219.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_220.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_221.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_222.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_223.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_224.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_225.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_226.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_227.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_228.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_229.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_230.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_231.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_232.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_233.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_234.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_235.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_236.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_237.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_238.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_239.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_240.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_241.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_242.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_243.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_244.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_245.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_246.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_247.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_248.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_249.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_250.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_251.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_252.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_253.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_254.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_255.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_256.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_257.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_258.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_259.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_260.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_261.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_262.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_263.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_264.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_265.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_266.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_267.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_268.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_269.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_270.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_271.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_272.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_273.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_274.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_275.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_276.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_277.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_278.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_279.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_280.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_281.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_282.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_283.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_284.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_285.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_286.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_287.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_288.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_289.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_290.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_291.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_292.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_293.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_294.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_295.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_296.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_297.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_298.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_299.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_300.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_301.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_302.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_303.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_304.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_305.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_306.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_307.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_308.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_309.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_310.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_311.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_312.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_313.geometry}
        material={materials['Default Material']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_314.geometry}
        material={materials['Default Material']}
      />
    </group>
  )
}

useGLTF.preload('/models/WoodenTruss.glb')
